name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - "closed"
    branches: [ main ]

env:
  flutter_version: "2.x"
  java_version: "12.x"

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
          
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Lint
        run: flutter analyze
        continue-on-error: true
        
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint_test_report
          path: ${{ github.workspace }}

      - name: Test
        run: flutter test

     
      - name: Build Apk
        run: flutter build apk --debug


# jobs:

#   test:
    
#     name: Run Unit Tests
#     runs-on: ubuntu-latest
#     steps:

      # - uses: actions/checkout@v1

      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: '12.x'
      # - uses: subosito/flutter-action@v1
      #   with:
      #     flutter-version: '2.x'
      # - run: flutter pub get
      # - run: flutter test

      # - run: flutter build apk

      # - name: set up JDK 11
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 11

      # - name: set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8

      # - name: Build with Gradle
      #   run: ./gradlew build

      # - name: Unit tests
      #   run: bash ./gradlew test --stacktrace

      # - name: set up flutter sdk
      #   uses: subosito/flutter-action@v1
      #   with:
      #     flutter-version: '1.22'
      # - run: flutter pub get
      # - run: flutter test

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v2

      # - name: Run lint
      #   run: ./gradlew lintDebug

      # - name: Upload html test report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: lint.html
      #     path: app/build/reports/lint-results-debug.html

      

      # - name: Unit tests
      #   run: ./android/gradlew test
        
      # - name: Upload test report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: unit_test_report
      #     path: app/build/reports/tests/testDebugUnitTest/  